# Copyright (c) 2026, Sidharth P V and contributors
# For license information, please see license.txt

"""Shared test fixture helpers, used by most floorgraph test files.

A bare CI/test site never runs ERPNext's setup wizard, and --skip-test-records
means Frappe's test runner won't auto-generate the usual test Company either
-- every floorgraph test that creates a Company, Item, Workstation, etc.
needs both of these first. Previously each test_*.py file defined its own
copy of this pair; consolidated here since scheduling_run's tests already
import helpers from schedule_slot's test file, so cross-test-file imports
are an established pattern, not a new one.
"""

import frappe

TEST_COMPANY = "_Test Company"


def ensure_setup_wizard_fixtures(country="India"):
	# Item Group "Products"/"Raw Material", UOM "Nos", Warehouse Type
	# "Transit", etc. are normally seeded by ERPNext's setup wizard - which
	# a bare test/CI site never runs. Call the setup wizard's own installer
	# rather than hand-picking individual masters: it's idempotent (every
	# record uses ignore_if_duplicate=True with a savepoint per record), so
	# calling it repeatedly across tests is safe.
	from erpnext.setup.setup_wizard.operations.install_fixtures import install

	install(country=country)


def ensure_test_company(company_name=TEST_COMPANY, abbr="_TC"):
	# A test Company is normally an ERPNext test fixture, auto-generated by
	# Frappe's test runner - which --skip-test-records deliberately opts
	# out of. A plain .insert() here triggers the same on_update() side
	# effects a fixture-created company would (default warehouses incl.
	# "Finished Goods - <abbr>"/"Work In Progress - <abbr>", accounts, cost
	# center) via ERPNext's own Company controller - nothing here
	# reimplements that. company_name/abbr are parameters (not always
	# TEST_COMPANY/"_TC") so a test needing a second, distinct Company
	# (e.g. to exercise cross-company validation) can reuse this directly.
	if frappe.db.exists("Company", company_name):
		return
	ensure_setup_wizard_fixtures()
	frappe.get_doc(
		{
			"doctype": "Company",
			"company_name": company_name,
			"abbr": abbr,
			"default_currency": "INR",
			"country": "India",
			"chart_of_accounts": "Standard",
		}
	).insert(ignore_permissions=True)
